# Generated by Django 6.0.5 on 2026-05-19 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_merge_0004_product_image_0004_created_at_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_bill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
